# Site settings
title: My Portfolio
description: Emmanuel Victor Garcia's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emmanuel Garcia
user_description: I've worked with different programming languages. For mobile applications I use Java, Kotlin, Swift and Javascript. Whenever I start creating new projects, I learn new language.
user_title: Software Developer
email: emmanuelgvictor@gmail.com
twitter_username: lorem_ipsum
github_username:  yuelvic
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
